server:
  port: 8080

spring:
  application:
    name: wallet-service
  datasource:
    url: jdbc:h2:mem:walletdb;DB_CLOSE_DELAY=-1
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update # Em produção, usar 'validate' ou uma ferramenta de migração como Flyway/Liquibase
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Configurações de segurança e JWT
jwt:
  secret: "YOUR_SUPER_SECRET_JWT_KEY_CHANGE_ME_AND_PUT_IN_VAULT_IN_PRODUCTION_a9f8e7d6c5b4a3e2d1c0b9a8f7e6d5c4b3a2e1d0"
  expiration:
    access-token-ms: 3600000 # 1 hora